import 'package:cloud_firestore/cloud_firestore.dart';

import '../../features/projects/presentation/project_providers.dart';
import '../network/api_response.dart';

/// Firebase Firestore implementation of [ProjectService].
///
/// Projects are stored in the `projects` collection with the following schema:
///
/// ```json
/// {
///   "name": "My Project",
///   "description": "...",
///   "status": "draft",          // enum string
///   "thumbnailUrl": "...",
///   "createdAt": Timestamp,
///   "updatedAt": Timestamp,
///   "mediaIds": ["media_1", ...],
///   "metadata": { ... }
/// }
/// ```
///
/// Each document ID is auto-generated by Firestore and used as [Project.id].
class FirestoreProjectService implements ProjectService {
  FirestoreProjectService({FirebaseFirestore? firestore})
      : _db = firestore ?? FirebaseFirestore.instance;

  final FirebaseFirestore _db;

  /// Reference to the `projects` collection.
  CollectionReference<Map<String, dynamic>> get _collection =>
      _db.collection('projects');

  // ---------------------------------------------------------------------------
  // Create
  // ---------------------------------------------------------------------------

  @override
  Future<Project> createProject(String name, {String? description}) async {
    try {
      final now = Timestamp.now();
      final data = <String, dynamic>{
        'name': name,
        'description': description,
        'status': ProjectStatus.draft.name,
        'thumbnailUrl': null,
        'createdAt': now,
        'updatedAt': now,
        'mediaIds': <String>[],
        'metadata': <String, dynamic>{},
      };

      final docRef = await _collection.add(data);

      return Project(
        id: docRef.id,
        name: name,
        description: description,
        status: ProjectStatus.draft,
        createdAt: now.toDate(),
        updatedAt: now.toDate(),
        mediaIds: const [],
        metadata: const {},
      );
    } on FirebaseException catch (e) {
      throw StateError('Failed to create project: ${e.message}');
    } catch (e) {
      throw StateError('Unexpected error creating project: $e');
    }
  }

  // ---------------------------------------------------------------------------
  // Read
  // ---------------------------------------------------------------------------

  @override
  Future<Project> getProject(String id) async {
    try {
      final snapshot = await _collection.doc(id).get();
      if (!snapshot.exists) {
        throw StateError('Project not found: $id');
      }
      return _docToProject(snapshot);
    } on FirebaseException catch (e) {
      throw StateError('Failed to get project: ${e.message}');
    } catch (e) {
      if (e is StateError) rethrow;
      throw StateError('Unexpected error fetching project: $e');
    }
  }

  @override
  Future<List<Project>> fetchProjects() async {
    try {
      final query = _collection.orderBy('createdAt', descending: true);
      final snapshot = await query.get();
      return snapshot.docs.map(_docToProject).toList();
    } on FirebaseException catch (e) {
      throw StateError('Failed to fetch projects: ${e.message}');
    } catch (e) {
      throw StateError('Unexpected error fetching projects: $e');
    }
  }

  /// Fetch a paginated list of projects.
  ///
  /// [limit] controls the page size (default 20).
  /// [lastDocId] is the document ID from the previous page to start after.
  Future<ApiResponse<List<Project>>> getProjects({
    int limit = 20,
    String? lastDocId,
  }) async {
    try {
      Query<Map<String, dynamic>> query =
          _collection.orderBy('createdAt', descending: true).limit(limit);

      if (lastDocId != null) {
        final lastDoc = await _collection.doc(lastDocId).get();
        if (lastDoc.exists) {
          query = query.startAfterDocument(lastDoc);
        }
      }

      final snapshot = await query.get();
      final projects = snapshot.docs.map(_docToProject).toList();
      return ApiResponse.success(projects);
    } on FirebaseException catch (e) {
      return ApiResponse.error('Failed to fetch projects: ${e.message}');
    } catch (e) {
      return ApiResponse.error('Unexpected error: $e');
    }
  }

  // ---------------------------------------------------------------------------
  // Update
  // ---------------------------------------------------------------------------

  @override
  Future<Project> updateProject(String id,
      {String? name, String? description, ProjectStatus? status}) async {
    try {
      final updates = <String, dynamic>{
        'updatedAt': Timestamp.now(),
      };
      if (name != null) updates['name'] = name;
      if (description != null) updates['description'] = description;
      if (status != null) updates['status'] = status.name;

      await _collection.doc(id).update(updates);
      return getProject(id);
    } on FirebaseException catch (e) {
      throw StateError('Failed to update project: ${e.message}');
    } catch (e) {
      if (e is StateError) rethrow;
      throw StateError('Unexpected error updating project: $e');
    }
  }

  /// Update arbitrary fields on a project document.
  Future<ApiResponse<void>> updateProjectFields(
      String id, Map<String, dynamic> data) async {
    try {
      data['updatedAt'] = Timestamp.now();
      await _collection.doc(id).update(data);
      return ApiResponse.success(null);
    } on FirebaseException catch (e) {
      return ApiResponse.error('Failed to update project: ${e.message}');
    } catch (e) {
      return ApiResponse.error('Unexpected error: $e');
    }
  }

  // ---------------------------------------------------------------------------
  // Delete
  // ---------------------------------------------------------------------------

  @override
  Future<void> deleteProject(String id) async {
    try {
      await _collection.doc(id).delete();
    } on FirebaseException catch (e) {
      throw StateError('Failed to delete project: ${e.message}');
    } catch (e) {
      throw StateError('Unexpected error deleting project: $e');
    }
  }

  // ---------------------------------------------------------------------------
  // Real-time stream
  // ---------------------------------------------------------------------------

  /// Returns a real-time stream of all projects, ordered by creation date.
  Stream<List<Project>> projectsStream() {
    return _collection
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs.map(_docToProject).toList());
  }

  /// Returns a real-time stream for a single project.
  Stream<Project?> projectStream(String id) {
    return _collection.doc(id).snapshots().map((snapshot) {
      if (!snapshot.exists) return null;
      return _docToProject(snapshot);
    });
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// Converts a Firestore [DocumentSnapshot] to a [Project] model.
  Project _docToProject(
      DocumentSnapshot<Map<String, dynamic>> snapshot) {
    final data = snapshot.data()!;
    return Project(
      id: snapshot.id,
      name: data['name'] as String? ?? '',
      description: data['description'] as String?,
      status: _parseStatus(data['status'] as String?),
      thumbnailUrl: data['thumbnailUrl'] as String?,
      createdAt: _parseTimestamp(data['createdAt']),
      updatedAt: _parseTimestamp(data['updatedAt']),
      mediaIds: (data['mediaIds'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const [],
      metadata: (data['metadata'] as Map<String, dynamic>?) ?? const {},
    );
  }

  /// Safely parses a [ProjectStatus] from a string, defaulting to [ProjectStatus.draft].
  ProjectStatus _parseStatus(String? value) {
    if (value == null) return ProjectStatus.draft;
    return ProjectStatus.values.firstWhere(
      (e) => e.name == value,
      orElse: () => ProjectStatus.draft,
    );
  }

  /// Safely converts a [Timestamp] or `DateTime` to [DateTime].
  DateTime _parseTimestamp(dynamic value) {
    if (value is Timestamp) return value.toDate();
    if (value is DateTime) return value;
    return DateTime(0);
  }
}
